"""METHODOLOGY.md + METHODOLOGY.lock generation.

The lock records a sha256 over every file that can change a published print
(factors.yaml, sovereign.yaml, index.py, normalise.py, weights.py) together with
the methodology version. The generator refuses to record a changed hash under an
unchanged version — unless the version carries a '-dev' suffix (pre-launch).
CI and pytest verify that the lock matches the working tree, so a methodology
change without a deliberate, versioned regeneration fails the build.
"""

from __future__ import annotations

import hashlib
from pathlib import Path

import yaml

from eucri import DISCLAIMER
from eucri.config import CONFIG_DIR, load_factors, load_sovereign

REPO_ROOT = Path(__file__).resolve().parents[2]
LOCK_PATH = REPO_ROOT / "METHODOLOGY.lock"
DOC_PATH = REPO_ROOT / "METHODOLOGY.md"

HASHED_FILES = (
    "config/factors.yaml",
    "config/sovereign.yaml",
    "src/eucri/index.py",
    "src/eucri/normalise.py",
    "src/eucri/weights.py",
)


def compute_hash(repo_root: Path | None = None) -> str:
    root = repo_root or REPO_ROOT
    h = hashlib.sha256()
    for rel in HASHED_FILES:
        path = root / rel
        h.update(rel.encode("utf-8"))
        h.update(b"\x00")
        content = path.read_bytes() if path.exists() else b"<absent>"
        h.update(content.replace(b"\r\n", b"\n"))  # hash must not depend on git eol conversion
        h.update(b"\x00")
    return h.hexdigest()


def read_lock(lock_path: Path | None = None) -> dict | None:
    path = lock_path or LOCK_PATH
    if not path.exists():
        return None
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def update_lock(repo_root: Path | None = None) -> dict:
    """Regenerate the lock; refuses a changed hash under an unchanged released version."""
    root = repo_root or REPO_ROOT
    version = load_factors(root / "config").methodology_version
    new_hash = compute_hash(root)
    lock_path = root / "METHODOLOGY.lock"
    lock = read_lock(lock_path) or {"current": None, "history": []}
    current = lock["current"]
    if current is not None and current["hash"] != new_hash:
        if current["version"] == version and not version.endswith("-dev"):
            raise SystemExit(
                f"methodology files changed but methodology_version is still {version!r}. "
                "Bump methodology_version in config/factors.yaml and add a CHANGELOG entry "
                "before regenerating the lock (see GOVERNANCE.md)."
            )
    if current is None or current["hash"] != new_hash or current["version"] != version:
        from eucri.db import utc_now_iso

        entry = {"version": version, "hash": new_hash, "generated_utc": utc_now_iso()}
        lock["current"] = {"version": version, "hash": new_hash}
        lock["history"] = lock.get("history", []) + [entry]
    lock_path.write_text(
        "# AUTO-GENERATED by `python -m eucri.run docs` — do not hand-edit.\n"
        + yaml.safe_dump(lock, sort_keys=False),
        encoding="utf-8",
    )
    return lock


def render_methodology(config_dir: Path | None = None) -> str:
    cfg_dir = config_dir or CONFIG_DIR
    f = load_factors(cfg_dir)
    sovereign = sorted(load_sovereign(cfg_dir))
    factors_yaml = (cfg_dir / "factors.yaml").read_text(encoding="utf-8")
    review = f.weights.review
    classes_table = "\n".join(
        f"| `{name}` | {mc.reference_variant} | "
        + ", ".join(f"{v} (x{factor:g})" for v, factor in mc.variants.items())
        + " |"
        for name, mc in f.model_classes.items()
    )
    weekdays = {1: "Monday", 2: "Tuesday", 3: "Wednesday", 4: "Thursday",
                5: "Friday", 6: "Saturday", 7: "Sunday"}
    anchor = weekdays.get(review.anchor_weekday, str(review.anchor_weekday))

    return f"""<!-- AUTO-GENERATED by `python -m eucri.run docs` from config/factors.yaml.
     Do not hand-edit; edit the config or eucri/methodology.py and regenerate. -->

# EU-CRI Methodology — v{f.methodology_version}

EU-CRI (EU Compute Rental Index) is a daily reference price for renting AI compute
delivered from data centres physically located in the EU/EEA. Headline series:
**EU-CRI-H100**, in USD per GPU-hour with a EUR companion series at the ECB reference
rate; companion class series (A100, B200) publish once they clear the source gate, and
**EU-CRI-COMPUTE** aggregates the class series into one chain-linked level.

## 1. Unit definition

One EU-CRI-H100 unit = one NVIDIA **{f.reference_unit.gpu_model}** 80GB GPU-hour,
**{f.reference_unit.term}** (no term commitment), datacenter-hosted, delivered from the
EU/EEA, per-GPU price in an **{f.reference_unit.node_gpus}-GPU NVLink node** configuration,
excluding storage and egress.

The index observes **model classes**; within a class, non-reference variants are
normalised to the reference variant via published multiplicative factors:

| Class | Reference variant | Variants (factor) |
|---|---|---|
{classes_table}

Excluded outright: variants not listed above (e.g. PCIe), community/consumer hosts,
interruptible/spot tiers ({", ".join(f.filters.exclude_tiers)}), term-committed prices,
offers below {f.filters.min_gpu_count} GPUs, prices outside the sanity band
[${f.filters.price_floor_usd:.2f}, ${f.filters.price_ceiling_usd:.2f}] per GPU-hour.

## 2. Data hierarchy (IOSCO P8)

Executable marketplace asks are preferred over list prices; executable-tier sources carry
a **{f.weights.executable_multiplier}x** weight multiplier inside the weight review
(§3.1). Overlay data (power prices) never enters the calculation. Competitor indices are
never ingested.

## 3. Aggregation (exact algorithm)

Per UTC day and series:

1. Collect all observations for the day passing the unit filters above.
2. **Representative price per provider** = the minimum surviving executable ask
   (marketplaces are single constituents, e.g. `vast.ai`), else the list price.
3. Static (manually verified) entries older than {f.staleness.exclude_days} days are
   excluded as stale (warning from {f.staleness.warn_days} days).
4. **Winsorise** the constituent price set at the
   {f.aggregation.winsorise_pct[0]:g}th/{f.aggregation.winsorise_pct[1]:g}th percentiles
   (nearest-rank; values outside are clamped to the boundary value).
5. **Weight** per constituent = its weight in the effective **weight review** (§3.1).
   A provider absent from the effective review enters at the default weight
   ({f.weights.default_capacity} capacity units, x{f.weights.executable_multiplier:g} if
   executable) and is flagged `no_weight_history` until the next review.
6. **Concentration cap**: no constituent may exceed
   {f.weights.max_weight_share_pct:g}% of a print's total weight; the excess is
   redistributed pro-rata over the uncapped constituents (iterated to a fixed point;
   the cap relaxes to 100/n when n constituents cannot satisfy it). Included
   constituents' published weights are the resulting shares, summing to 100.
7. **Weighted median**: sort by (price ascending, provider name); the index value is the
   first price at which cumulative share reaches 50% (lower weighted median, no
   interpolation).
8. **Publish gate**: fewer than {f.aggregation.min_providers} qualifying providers →
   no value is published; the print is flagged `insufficient_sources`. A gap is credible;
   a fabricated print is fatal.
9. EUR companion = USD value / most recent available ECB EUR/USD reference rate
   (rate and rate-date recorded on every print).
10. Headline companion: {f.aggregation.smoothing_days}-day mean of daily prints
    (requires ≥4 non-null days).

Constituent prices moving more than {f.jump_flag_pct:g}% day-over-day are flagged
(`jump`) for manual review but are **not** excluded.

### 3.1 Weight reviews (data-driven, scheduled)

Constituent weights are **data-driven and reviewed on a fixed schedule** — the same
mechanism commodity benchmarks use for periodic reweighting, compressed to this
market's pace. A review takes effect each **{anchor}** and is computed mechanically
from the trailing **{review.window_days}-day** observation window ending the day
before it takes effect:

- **Provider weight** = median over the provider's observed days of
  (daily qualifying capacity × tier multiplier) × presence ratio
  (days observed / collection days in the window). Daily qualifying capacity =
  min(sum of listed GPUs across qualifying executable asks, {f.weights.capacity_cap});
  list-price rows carry the default of {f.weights.default_capacity} — their
  multiplicity is region enumeration, not inventory.
- Weights are **fixed between reviews**: prices move the index daily, weights only
  move on review dates. Every review is stored append-only (`weight_sets` table) and
  printable via `python -m eucri.run weights --date YYYY-MM-DD`.
- **Bootstrap rule**: while the window holds fewer than {review.min_history_days}
  collection days, weights fall back to same-day observed capacity and every print is
  flagged `bootstrap_weights`.
- Reviews follow a fixed published formula with no discretion: a review is a **data
  update, not a methodology change**. Changing the formula or any parameter of it is
  a methodology change (§6).

### 3.2 EU-CRI-COMPUTE (chain-linked class composite)

The composite aggregates the class series into one level (base
{f.composite.base_value:g} at its first print), **chain-linked** so that reweighting
never jumps the published level:

- At each weight review, **class basket shares** = each class's share of total observed
  qualifying capacity over the window. With ≥2 eligible classes, shares are capped at
  {f.composite.max_class_share_pct:g}% and floored at {f.composite.min_class_share_pct:g}%
  (pro-rata redistribution, as in §3 step 6).
- Daily: composite(t) = composite(t−1) × Σ share × (class(t) / class(t−1)), summed over
  classes with a published value on both endpoints, shares renormalised over those
  classes. A class that gaps drops out of that day's link; if no class links, the
  composite gaps (`no_linkable_series`).
- As the observed market migrates across hardware generations (H100 → B200), the basket
  follows mechanically — no methodology change required.

## 4. Series

| Series | Constituents |
|---|---|
| `EU-CRI-H100` | all qualifying H100-class providers (headline) |
| `EU-CRI-H100-7D` | {f.aggregation.smoothing_days}-day mean of the headline |
| `EU-CRI-H100-SOV` | EU/EEA-headquartered operators: {", ".join(sovereign)} |
| `EU-CRI-H100-MKT` | executable-tier (marketplace) sources only |
| `EU-CRI-H100-CLOUD` | list-tier (cloud) sources only |
| `EU-CRI-A100`, `EU-CRI-B200` | class series; published once ≥{f.aggregation.min_providers} sources exist (gapped, with audit trail, before that) |
| `EU-CRI-COMPUTE` | chain-linked composite of class series (§3.2); a level, not a $/hr price |

## 5. Revisions and corrections

Raw observations and published prints are append-only (enforced by database triggers).
Errors are corrected in the next print as a **new revision** flagged `correction`; prior
revisions remain queryable forever. The full constituent set for any print is available
via `python -m eucri.run constituents --date YYYY-MM-DD`.

## 6. Changes to this methodology

Any change to the parameters below or the calculation code requires a version bump, a
CHANGELOG entry, and one publication's notice before taking effect — enforced
mechanically via `METHODOLOGY.lock` in CI. See GOVERNANCE.md.

## 7. Current parameters (config/factors.yaml, verbatim)

```yaml
{factors_yaml.rstrip()}
```

## 8. IOSCO Principles mapping

| IOSCO principle | Implementation |
|---|---|
| Benchmark design & data sufficiency (P6–P7) | Observable, executable marketplace quotes anchored; ≥{f.aggregation.min_providers}-source rule; weights set by observed data on a fixed schedule; {f.weights.max_weight_share_pct:g}% concentration cap; no expert judgement in the calculation path |
| Hierarchy of data inputs (P8) | Executable quotes weighted {f.weights.executable_multiplier}x over list prices inside the weight review; overlay data never enters the calculation |
| Transparency of methodology (P9, P11) | This document is auto-generated from config, semver-versioned; every parameter is a visible config value; every weight review is stored and queryable |
| Changes to methodology (P12) | CHANGELOG + one-publication notice before any parameter change takes effect; hash-locked in CI. Scheduled weight reviews follow the fixed published formula and are data updates, not methodology changes |
| Quality of the administrator (P4–P5) | Named author; stated conflicts (the author may trade venues the index observes — disclosed); corrections never silent |
| Complaints & audit trail (P13, P16) | Raw observations and weight reviews immutable in SQLite; any reader can request the constituent set for a given day |

---

*{DISCLAIMER}*

*Author and administrator: Mark Rusch (rusch.mh@gmail.com). Conflicts: the author may
hold positions on venues whose prices the index observes; see GOVERNANCE.md.*
"""


def generate(repo_root: Path | None = None) -> None:
    root = repo_root or REPO_ROOT
    update_lock(root)
    (root / "METHODOLOGY.md").write_text(
        render_methodology(root / "config"), encoding="utf-8", newline="\n"
    )
