"""METHODOLOGY.md + METHODOLOGY.lock generation.

The lock records a sha256 over every file that can change a published print
(factors.yaml, sovereign.yaml, index.py, normalise.py) together with the
methodology version. The generator refuses to record a changed hash under an
unchanged version — unless the version carries a '-dev' suffix (pre-launch).
CI and pytest verify that the lock matches the working tree, so a methodology
change without a deliberate, versioned regeneration fails the build.
"""

from __future__ import annotations

import hashlib
from pathlib import Path

import yaml

from eucri import DISCLAIMER
from eucri.config import CONFIG_DIR, load_factors, load_sovereign

REPO_ROOT = Path(__file__).resolve().parents[2]
LOCK_PATH = REPO_ROOT / "METHODOLOGY.lock"
DOC_PATH = REPO_ROOT / "METHODOLOGY.md"

HASHED_FILES = (
    "config/factors.yaml",
    "config/sovereign.yaml",
    "src/eucri/index.py",
    "src/eucri/normalise.py",
)


def compute_hash(repo_root: Path | None = None) -> str:
    root = repo_root or REPO_ROOT
    h = hashlib.sha256()
    for rel in HASHED_FILES:
        path = root / rel
        h.update(rel.encode("utf-8"))
        h.update(b"\x00")
        content = path.read_bytes() if path.exists() else b"<absent>"
        h.update(content.replace(b"\r\n", b"\n"))  # hash must not depend on git eol conversion
        h.update(b"\x00")
    return h.hexdigest()


def read_lock(lock_path: Path | None = None) -> dict | None:
    path = lock_path or LOCK_PATH
    if not path.exists():
        return None
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def update_lock(repo_root: Path | None = None) -> dict:
    """Regenerate the lock; refuses a changed hash under an unchanged released version."""
    root = repo_root or REPO_ROOT
    version = load_factors(root / "config").methodology_version
    new_hash = compute_hash(root)
    lock_path = root / "METHODOLOGY.lock"
    lock = read_lock(lock_path) or {"current": None, "history": []}
    current = lock["current"]
    if current is not None and current["hash"] != new_hash:
        if current["version"] == version and not version.endswith("-dev"):
            raise SystemExit(
                f"methodology files changed but methodology_version is still {version!r}. "
                "Bump methodology_version in config/factors.yaml and add a CHANGELOG entry "
                "before regenerating the lock (see GOVERNANCE.md)."
            )
    if current is None or current["hash"] != new_hash or current["version"] != version:
        from eucri.db import utc_now_iso

        entry = {"version": version, "hash": new_hash, "generated_utc": utc_now_iso()}
        lock["current"] = {"version": version, "hash": new_hash}
        lock["history"] = lock.get("history", []) + [entry]
    lock_path.write_text(
        "# AUTO-GENERATED by `python -m eucri.run docs` — do not hand-edit.\n"
        + yaml.safe_dump(lock, sort_keys=False),
        encoding="utf-8",
    )
    return lock


def render_methodology(config_dir: Path | None = None) -> str:
    cfg_dir = config_dir or CONFIG_DIR
    f = load_factors(cfg_dir)
    sovereign = sorted(load_sovereign(cfg_dir))
    factors_yaml = (cfg_dir / "factors.yaml").read_text(encoding="utf-8")

    return f"""<!-- AUTO-GENERATED by `python -m eucri.run docs` from config/factors.yaml.
     Do not hand-edit; edit the config or eucri/methodology.py and regenerate. -->

# EU-CRI Methodology — v{f.methodology_version}

EU-CRI (EU Compute Rental Index) is a daily reference price for renting AI compute
delivered from data centres physically located in the EU/EEA. Headline series:
**EU-CRI-H100**, in USD per GPU-hour with a EUR companion series at the ECB reference rate.

## 1. Unit definition

One EU-CRI-H100 unit = one NVIDIA **{f.reference_unit.gpu_model}** 80GB GPU-hour,
**{f.reference_unit.term}** (no term commitment), datacenter-hosted, delivered from the
EU/EEA, per-GPU price in an **{f.reference_unit.node_gpus}-GPU NVLink node** configuration,
excluding storage and egress.

Excluded outright: PCIe variants, community/consumer hosts, interruptible/spot tiers
({", ".join(f.filters.exclude_tiers)}), term-committed prices, offers below
{f.filters.min_gpu_count} GPUs, prices outside the sanity band
[${f.filters.price_floor_usd:.2f}, ${f.filters.price_ceiling_usd:.2f}] per GPU-hour.
Normalised in: H100 NVL 94GB via a published adjustment factor
(current: {f.adjustment_factors.get("H100_NVL_94GB", 1.0)}).

## 2. Data hierarchy (IOSCO P8)

Executable marketplace asks are preferred over list prices; executable-tier sources carry
a **{f.weights.executable_multiplier}x** weight multiplier. Overlay data (power prices)
never enters the calculation. Competitor indices are never ingested.

## 3. Aggregation (exact algorithm)

Per UTC day and series:

1. Collect all observations for the day passing the unit filters above.
2. **Representative price per provider** = the minimum surviving executable ask
   (marketplaces are single constituents, e.g. `vast.ai`), else the list price.
3. Static (manually verified) entries older than {f.staleness.exclude_days} days are
   excluded as stale (warning from {f.staleness.warn_days} days).
4. **Winsorise** the constituent price set at the
   {f.aggregation.winsorise_pct[0]:g}th/{f.aggregation.winsorise_pct[1]:g}th percentiles
   (nearest-rank; values outside are clamped to the boundary value).
5. **Weight** per constituent = min(available GPU count, {f.weights.capacity_cap}) where
   observable, else {f.weights.default_capacity}; multiplied by
   {f.weights.executable_multiplier} for executable-tier sources.
6. **Weighted median**: sort by (price ascending, provider name); the index value is the
   first price at which cumulative weight reaches 50% of total weight (lower weighted
   median, no interpolation).
7. **Publish gate**: fewer than {f.aggregation.min_providers} qualifying providers →
   no value is published; the print is flagged `insufficient_sources`. A gap is credible;
   a fabricated print is fatal.
8. EUR companion = USD value / most recent available ECB EUR/USD reference rate
   (rate and rate-date recorded on every print).
9. Headline companion: {f.aggregation.smoothing_days}-day mean of daily prints
   (requires ≥4 non-null days).

Constituent prices moving more than {f.jump_flag_pct:g}% day-over-day are flagged
(`jump`) for manual review but are **not** excluded.

## 4. Series

| Series | Constituents |
|---|---|
| `EU-CRI-H100` | all qualifying providers |
| `EU-CRI-H100-7D` | {f.aggregation.smoothing_days}-day mean of the headline |
| `EU-CRI-H100-SOV` | EU/EEA-headquartered operators: {", ".join(sovereign)} |
| `EU-CRI-H100-MKT` | executable-tier (marketplace) sources only |
| `EU-CRI-H100-CLOUD` | list-tier (cloud) sources only |

A100/B200 series will be added when ≥{f.aggregation.min_providers} sources exist.

## 5. Revisions and corrections

Raw observations and published prints are append-only (enforced by database triggers).
Errors are corrected in the next print as a **new revision** flagged `correction`; prior
revisions remain queryable forever. The full constituent set for any print is available
via `python -m eucri.run constituents --date YYYY-MM-DD`.

## 6. Changes to this methodology

Any change to the parameters below or the calculation code requires a version bump, a
CHANGELOG entry, and one publication's notice before taking effect — enforced
mechanically via `METHODOLOGY.lock` in CI. See GOVERNANCE.md.

## 7. Current parameters (config/factors.yaml, verbatim)

```yaml
{factors_yaml.rstrip()}
```

## 8. IOSCO Principles mapping

| IOSCO principle | Implementation |
|---|---|
| Benchmark design & data sufficiency (P6–P7) | Observable, executable marketplace quotes anchored; ≥{f.aggregation.min_providers}-source rule; no expert judgement in the calculation path |
| Hierarchy of data inputs (P8) | Executable quotes weighted {f.weights.executable_multiplier}x over list prices; overlay data never enters the calculation |
| Transparency of methodology (P9, P11) | This document is auto-generated from config, semver-versioned; every parameter is a visible config value |
| Changes to methodology (P12) | CHANGELOG + one-publication notice before any parameter change takes effect; hash-locked in CI |
| Quality of the administrator (P4–P5) | Named author; stated conflicts (the author may trade venues the index observes — disclosed); corrections never silent |
| Complaints & audit trail (P13, P16) | Raw observations immutable in SQLite; any reader can request the constituent set for a given day |

---

*{DISCLAIMER}*

*Author and administrator: Mark Rusch (rusch.mh@gmail.com). Conflicts: the author may
hold positions on venues whose prices the index observes; see GOVERNANCE.md.*
"""


def generate(repo_root: Path | None = None) -> None:
    root = repo_root or REPO_ROOT
    update_lock(root)
    (root / "METHODOLOGY.md").write_text(
        render_methodology(root / "config"), encoding="utf-8", newline="\n"
    )
